language: node_js
sudo: false
node_js:
  - "10"

before_script:
  - npm install 
  - npm install nightwatch

script:
  - node node_modules/nightwatch/bin/runner.js -e chrome -a login
  # - npm run-script coverage
